language: node_js
node_js:
- 0.12
- 4
- node
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_install: npm install -g electron-prebuilt
script: npm run test
notifications:
  email: false
  slack:
    secure: 66MUg2Vhdi4izNbzHvgNRNy7Fzwom1MHx87rkXpxeo2uWSiiHy8uLM0+kqZBitwbgrAIba2YmxP0GlEvZBRLETWr2wgAAk06Hagfs9vJqQty6NyVSYkYc1YLg0ZDgYD6r/2ms7ObxVU/2w+mPF7kZuJn/3H2u9XVAFquTyCWfK7triW+gS8Syxk0OpuXLXz5XcJq7F4mUNMJwd2OgaGMQVKod1G24i1wEHEHmoRLkF6g6MIiatfi+iIpSvAfp37d2cmxHY35TIebZttvd255A/1w5z0xbtIb8rXjcBOx3ykqairbkJVw8WSkj35vWrc/MaADQ79XuEtqFkVgeCPMJaAtWnEZ12DoZsWmEOq7ZFGvbHyG28blSiXKuJ8cFvui/ujEC3VL9PUpG9bYvCzKqtVMB3BVJiEk5MO/Gx0yf6X/z9MIImFSC6FbtDO/eU4LF9qy/YZQGw49dVBjxYzk04i87jE4VGoYmoGto2bvycNRbNDoFzI2BKexXwK/CBrCU+4p1HDSxMl/H9nQBxhFgytZUyF6DTahQ8kuFgu37FImfeF/04wQC1bVLtE7g9bkFgLIoYG9zqprYPivDTHF9gUB7PPhY1SbrWAcJIgp1B7DL0UL8FLcK8ype8x0PIEkKhv0ygXttXurYtzzeTl2bJXF2bdhVim+rVXdKl/vuRw=
